apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scanners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sitardaniel/pipelineguard-gitops
    targetRevision: HEAD
    path: apps/scanners
  destination:
    server: https://kubernetes.default.svc
    namespace: pipelineguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
